project:
  type: website

website:
  title: "Rapport"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - text: Modèles
        menu:
          - href: models/reglog.qmd
            text: Regréssions Logistiques
          - href: models/lasso.qmd
            text: Régression Lasso
          - href: models/random.qmd
            text: Forêt Aléatoire
          - href: models/boosting.qmd
            text: Boosting

format:
  html:
    theme: minty
    css: styles.css
    toc: true



