project:
  type: website

execute:
  enabled: true
  freeze: auto

exclude:
  - notebooks/TP.ipynb

jupyter: .venv/bin/python3

website:
  title: "Stress des élèves dans le supérieur"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - text: Modèles
        menu:
          - href: models/reglog.qmd
            text: Régressions logistiques
          - href: models/random.qmd
            text: Forêt aléatoire
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: minty
    css: styles.css
    toc: true